add_subdirectory(Utils)
add_subdirectory(GraphCore)
add_subdirectory(Geometry)
add_subdirectory(LayoutEngine)
add_subdirectory(Persistence)
add_subdirectory(Evidence)
add_subdirectory(FileManager)

IF(NOT TESTING)
# add_subdirectory(VisualState)
add_subdirectory(Styles)
add_subdirectory(GraphQt)
add_subdirectory(Terminal)
endif()

